name: Sancus validation
on:
  # Run on pushes to master
  push:
    branches:
      - main
  # run on manual trigger
  workflow_dispatch:
  # Run on pull requests (automatically uses PR in docker name)
  pull_request:
  # Also run on a schedule (once a month)
  schedule:
    - cron: '0 0 1 */1 *'

jobs:
  matrix-gen:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:
      - uses: actions/checkout@v2
      - id: list_dirs
        run: |
          cd sancus/
          MATRIX=$(find -mindepth 2 -type d | jq -cnR '[inputs | select(length>0)]')
          echo $MATRIX
          echo "::set-output name=matrix::$MATRIX"
  
  test:
    runs-on: ubuntu-22.04
    needs: matrix-gen
    strategy:
      fail-fast: false
      matrix:
        testcase: ${{fromJson(needs.matrix-gen.outputs.matrix)}}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install pandora/angr dependencies
        run: |
          sudo apt-get install python3 python3-pip python3-venv -y
          git clone https://github.com/pandora-tee/pandora && cd pandora
          git clone https://github.com/angr/angr-platforms
          python3 -m venv .venv && . .venv/bin/activate && python3 -m pip install -r requirements.txt && cd angr-platforms && python3 -m pip install .
      - name: Symbolic validation of ${{ matrix.testcase }}
        run: |
          cd ${{ github.workspace }}/pandora/
          source .venv/bin/activate
          ./pandora.py run -n 30 -p ptr,cf --pandora-option PANDORA_EXPLORE_STACK_DEPTH=1500 ${{ github.workspace }}/sancus/${{ matrix.testcase }}/main.elf
